[package]
name = "cs_api_testing"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = { version = "1.0.141" }
reqwest = { version = "0.12.22", features = ["json", "brotli"] }
whoami = { version = "1.6.0" }
rusqlite = { version = "0.37.0" }
tokio = { version = "1.46.1" } # features = ["full"]
flate2 = { version = "1.1.2" }
umya-spreadsheet = { version = "2.3.1" }
urlencoding = { version = "2.1.3" }
strum = { version = "0.27.2", features = ["derive"] }
# indexmap = { version = "2.10.0" }
rand = { version = "0.9.2" }
regex = { version = "1.11.1" }
chrono = { version = "0.4.41" }
iced = { git = "https://github.com/iced-rs/iced.git", branch = "master", features = ["tokio", "sipper", "image"]}
# iced_gif = "0.13.0"
num-traits = "0.2.19"
rfd = { version = "0.15.4", features = ["file-handle-inner"] }
# iced_futures = "0.13.2"
# futures = "0.3.31"

 